const mongoose = require("mongoose");

const EmployeeOrderSchema = new mongoose.Schema(
  {
    username: {type: String,
            required: true,},
    employeeId: {type: String,
              required: true,},
    product1: {type: String,
              required: true,},
    product2: {type: String,},
    product3: {type: String,},
    product4: {type: String,},
    product5: {type: String,},
    product6: {type: String,},
    product7: {type: String,},
    product8: {type: String,},
    product9: {type: String,},
    product10: {type: String,},
    product11: {type: String,},
    product12: {type: String,},
    product13: {type: String,},
    product14: {type: String,},
    product15: {type: String,},
    product16: {type: String,},
    product17: {type: String,},
    product18: {type: String,},
    product19: {type: String,},
    product20: {type: String,},
    product21: {type: String,},
    product22: {type: String,},
    product23: {type: String,},
    product24: {type: String,},
    product25: {type: String,},
    product26: {type: String,},
    product27: {type: String,},
    product28: {type: String,},
    product29: {type: String,},
    product30: {type: String,},                  
    quantity1: {type: String,
              required: true,
             },
    quantity2: {type: String,},
    quantity3: {type: String,},
    quantity4: {type: String,},
    quantity5: {type: String,},
    quantity6: {type: String,},
    quantity7: {type: String,},
    quantity8: {type: String,},
    quantity9: {type: String,},
    quantity10: {type: String,},
    quantity11: {type: String,},
    quantity12: {type: String,},
    quantity13: {type: String,},
    quantity14: {type: String,},
    quantity15: {type: String,},
    quantity16: {type: String,},
    quantity17: {type: String,},
    quantity18: {type: String,},
    quantity19: {type: String,},
    quantity20: {type: String,},
    quantity21: {type: String,},
    quantity22: {type: String,},
    quantity23: {type: String,},
    quantity24: {type: String,},
    quantity25: {type: String,},
    quantity26: {type: String,},
    quantity27: {type: String,},
    quantity28: {type: String,},
    quantity29: {type: String,},
    quantity30: {type: String,},
    price1: {type: String,},
    price2: {type: String,},
    price3: {type: String,},
    price4: {type: String,},
    price5: {type: String,},
    price6: {type: String,},
    price7: {type: String,},
    price8: {type: String,},
    price9: {type: String,},
    price10: {type: String,},
    price11: {type: String,},
    price12: {type: String,},
    price13: {type: String,},
    price14: {type: String,},
    price15: {type: String,},
    price16: {type: String,},
    price17: {type: String,},
    price18: {type: String,},
    price19: {type: String,},
    price20: {type: String,},
    price21: {type: String,},
    price22: {type: String,},
    price23: {type: String,},
    price24: {type: String,},
    price25: {type: String,},
    price26: {type: String,},
    price27: {type: String,},
    price28: {type: String,},
    price29: {type: String,},
    price30: {type: String,},
 
    address: {
                type: String,
                required: true,
              },
    pangst: {
                type: String,
                required: true,
              },
    draglicence: {
                type: String,
              },
    orderstatus: {
                type: String,
                required: true,
              },
    paymentstatus: {
                type: String,
              
              },
     paymentmethod: {
                type: String,
                
              },

    mrp: {
                type: String,
                required: true,
              },
    customername: {
                type: String,
                required: true,
              },

    customermobile: {
                type: String,
                required: true,
              },
    customeremail: {
                type: String,
              
              },
   deliveryboy: {
               type: String,
             },
  shopname: {
                type: String,
                required: true,
              },
  due: {
                type: String,
              },        

    orderDate: {type:Date},
    orderUpdateDate: {type:Date},

  },
);

module.exports = mongoose.model("EmployeeOrder", EmployeeOrderSchema);